extends: standard
rules:
  semi: [error, always]
  quotes: [error, double]
  comma-dangle: [error, always-multiline]
  no-tabs: off
  camelcase: off
  no-return-await: off
  no-return-assign: off
  no-unused-vars: warn
  padded-blocks: off
  no-trailing-spaces: off

  indent:
  - error
  - tab
  - SwitchCase: 1

  no-multiple-empty-lines:
  - error
  - max: 2
    maxEOF: 1
    maxBOF: 0

